identifier: ego_controller
name: ego_controller
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - gpio
  - i2c
  - counter
  - spi
  - usb_device
  - nvs
  - can
  - kscan
  - ble
  - pwm
